### ISSUE TITLE
 copy_encrypted_ami.sh: error: KMS Key arn:aws:kms:us-east-1:******* non existent, in the wrong region, or not enabled. Aborting.

### ISSUE THREAD

**Issue by AkshayTilekar** [aws-samples/copy-encrypted-ami#1]
I have created and enabled KMS key still it is showing me above error

**Comment by rollucas** [comment]
Hi , thanks for reporting the issue, can you confirm your KMS key is in the destination region and enabled?

Also, you could test the command below (replacing CMK_ID):

aws --region us-east-1  kms describe-key --key-id CMK_ID

Please do NOT share the output, just confirm if it's listed and enabled.
