### ISSUE TITLE
aws ec2 wait snapshot-completed times out often

### ISSUE THREAD

**Issue by richpage** [aws-samples/copy-encrypted-ami#2]
Hi,

I found that, quite often, the "aws ec2 wait snapshot-completed" would timeout waiting for snapshots to complete. That command has a hardcoded limit of 10 minutes.

My shell scripting is horrific, but, for what it's worth, I ended up adding a loop on the "describe-snapshots" command that waits for the snapshots to complete (for as long as it takes...).

I stole the idea and most of the code from : 
https://gist.github.com/sgnn7/d27fb0ab6e2cb29d466198ced9ea93df

I hope this helps someone that was running into the same problem.

```
...
i=0
while read snapshotid; do

    snapshot_progress="0%"
    while [ "$snapshot_progress" != "100%" ]; do
        snapshot_progress=$(aws ec2 describe-snapshots --region ${DST_REGION} \
                                                       --snapshot-ids ${DST_SNAPSHOT[i]} \
                                                       --profile ${DST_PROFILE} \
                                                       --no-paginate \
                                                       --query "Snapshots[*].Progress" \
                                                       --output text)
      echo "Snapshot progress: ${DST_SNAPSHOT[i]} $snapshot_progress"
      sleep 10
    done

    aws ec2 wait snapshot-completed --snapshot-ids ${DST_SNAPSHOT[i]} --profile ${DST_PROFILE} --region ${DST_REGION}

    i=$(( $i + 1 ))
done <<< "$SNAPSHOT_IDS"
echo -e "${COLOR}EBS Snapshots copies completed ${NC}"
...
```

**Comment by rollucas** [comment]
Thanks @richpage for the feedback! I will look into add same / or similar logic to the script. Will update here when it's done.

**Comment by rollucas** [comment]
Issues fixed! Thanks for your suggestion @richpage . Closing this now.
