### ISSUE TITLE
Error on trying to copy AMI with associated ephemeral devices

### ISSUE THREAD

**Issue by man8** [aws-samples/copy-encrypted-ami#5]
Hi, thank you for this handy tool.  On trying to copy an AMI, I ran into an error like this:

    $ copy_encrypted_ami.sh -s src -d dst -a ami-04f386a8fa9b55blah 
    Source region: eu-west-1
    Destination region: eu-west-1
    Destination account ID: blah
    Snapshots found: snap-012a6c6688943blah snap-06ae1c9807c77blah null null null null null null null null null null null null null null null null null null null null null null null null null null

    An error occurred (InvalidParameterValue) when calling the DescribeSnapshots operation: Value (null) for parameter snapshotId is invalid. Expected: 'snap-...'.
    Customer managed KMS key(s) used on source AMI:
    usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
    To see help text, you can run:

      aws help
      aws <command> help
      aws <command> <subcommand> help
    aws: error: argument --key-id: expected one argument
     copy_encrypted_ami.sh: error: Unable to retrieve the Key Manager information. Aborting. 

Exploring the BlockDeviceMappings section of the AMI metadata, I see:

    $ aws ec2 describe-images --profile src --region eu-west-1 --image-id ami-04f386a8fa9b55blah  --query 'Images[0]'|jq .BlockDeviceMappings
     [
       {
         "DeviceName": "/dev/sda1",
         "Ebs": {
           "Encrypted": true,
           "DeleteOnTermination": true,
           "VolumeType": "gp2",
           "VolumeSize": 100,
           "SnapshotId": "snap-012a6c6688943blah"
         }
       },
       {
         "DeviceName": "/dev/sdf",
         "Ebs": {
           "Encrypted": true,
           "DeleteOnTermination": true,
           "VolumeType": "gp2",
           "VolumeSize": 500,
           "SnapshotId": "snap-06ae1c9807c77blah"
         }
       },
       {
         "DeviceName": "xvdca",
         "VirtualName": "ephemeral0"
       },
       {
         "DeviceName": "xvdcb",
         "VirtualName": "ephemeral1"
       },
       {
         "DeviceName": "xvdcc",
         "VirtualName": "ephemeral2"
       },
       {
         "DeviceName": "xvdcd",
         "VirtualName": "ephemeral3"
       },
       {
         "DeviceName": "xvdce",
         "VirtualName": "ephemeral4"
       },
       {
    [.....]

It seems that we would want to skip emphemeral devices when finding snapshots to copy. I'll submit a quick pull request with a proposed solution.

**Comment by man8** [comment]
PR [here](https://github.com/aws-samples/copy-encrypted-ami/pull/6).

**Comment by rollucas** [comment]
Thanks for this @man8 ! I added a comment in the PR.

**Comment by rollucas** [comment]
PR merged : https://github.com/aws-samples/copy-encrypted-ami/pull/6

Thanks again @man8
