### ISSUE TITLE
Windows AMI supported?

### ISSUE THREAD

**Issue by linuxus** [aws-samples/copy-encrypted-ami#7]
Was wondering if this script does support my custom MS Windows AMI baked with un-encrypted snapshot.

Awsome tool and thanks!

**Comment by rollucas** [comment]
Hi @linuxus , just to clarify, you want to copy your un-encrypted Windows AMI into an encrypted one ?

**Comment by linuxus** [comment]
Hey Lucas, yes. That's the obejective.

**Comment by rollucas** [comment]
@linuxus There is a current limitation where you need at least 1 encrypted volume in the origin, otherwise the script will fail. The fact that's Windows AMI should not be a problem. I will look into fix that, thank for bringing this up.

**Comment by rollucas** [comment]
Hi @linuxus , I have just updated the script to overcome that limitation. Please try again if you can. I will resolve this issue but feel free to reopen if you still facing problems.
