### ISSUE TITLE
Unable to copy unencrypted AMI

### ISSUE THREAD

**Issue by shashwatapal** [aws-samples/copy-encrypted-ami#9]
Hi, 
I am unable to copy unencrypted AMI from account A to encrypted AMI in account B, I am getting the below error:
command used
./copy_encrypted_ami.sh -s xxxxx -d yyyyy -a ami-zzzzzzzzz -k arn:aws:kms:us-east-1:12345678:key/fgdfgdffgdfhdghfdhdh -l us-east-1 -r us-east-1 -n 

Customer managed KMS key(s) used on source AMI:
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws.exe: error: argument --key-id: expected one argument
 copy_encrypted_ami.sh: error: Unable to retrieve the Key Manager information. Aborting.

**Comment by rollucas** [comment]
Hi @shashwatapal , thanks for reporting the issue. Are you running the script in a Windows box? If so, please tell me what version so I can test it. Thanks

**Comment by shashwatapal** [comment]
We tried running the script on a Amazon Linux 2 server.

**Comment by rollucas** [comment]
Hi @shashwatapal  , I have just updated the script to overcome that limitation. Please try again if you can. I will resolve this issue but feel free to reopen if you still facing problems.
